POST http://localhost/api/sms.send
Content-Type: application/json
X-Session: 6Cnp1WDnjKvVWlWDkRf5geh4DFh18sSVNYrCQdVMjowuznxzAPkRGkZqnMIXBz2y

{
    "phone_number":"79098280707"
}
###
POST http://localhost/api/sms.verify
Content-Type: application/json
X-Session: 6Cnp1WDnjKvVWlWDkRf5geh4DFh18sSVNYrCQdVMjowuznxzAPkRGkZqnMIXBz2y

{
    "sms_code":"43025"
}
###
POST http://localhost/api/logout
Authorization: Bearer zv7DcUL0FnxpUGzzht57pGdfbuRluoZ56NjyFc4TIvF3Y1lrR1pcGFZ0YDNRnBRo
