POST http://localhost/api/products.get
Content-Type: application/json

{
    "page_size":5,
    "page":1,
    "search_string":"et n",
    "category_ids":[1,2],
    "brand_ids":[1],
    "sizes":["S"],
    "color_ids":[1],
    "material_ids":[1],
    "sort_price":false,
    "sort_new":true,
    "price_min":100,
    "price_max":1000
}
###
GET http://localhost/api/products.meta
###
GET http://localhost/api/product.get?id=2