### Генерация и отправка смс кода
POST http://localhost/api/sms.send
Content-Type: application/json
# X-Session: dBQm7Ul0Tdw3JunyVHpmTZ2aMwnf4VLqVcNYeIWXvCSFBMmCYhf4vCPHFMCn82tD

{
    "phone_number":"79098280706"
}
### Отправка кода на проверку
POST http://localhost/api/sms.verify
Content-Type: application/json
X-Session: SzkxXS8g72UigQuM7pT2mhhXLOY0agot1WwuRjbPcsonfk7YUJQUdxzFIte4tRag

{
    "sms_code":"3239"
}
### Удаление токена
POST http://localhost/api/logout
Authorization: Bearer zv7DcUL0FnxpUGzzht57pGdfbuRluoZ56NjyFc4TIvF3Y1lrR1pcGFZ0YDNRnBRo
