### Добавление в корзину
POST http://localhost/api/cart.add
Content-Type: application/json

{
    "product_id":3,
    "size":"L"
}
### Удаление из корзины
POST http://localhost/api/cart.delete
Content-Type: application/json
# X-Session: WuqN1tjZWW5suU4nCyCABeijpz1SEbUl2RGpRq2zh4M0nliHvF4B0knEiMwZWvlf
Authorization: Bearer usertoken

{
    "position_id":7
}
### Получение id товаров в корзине с размерами
GET http://localhost/api/cart.getIds
# X-Session: WuqN1tjZWW5suU4nCyCABeijpz1SEbUl2RGpRq2zh4M0nliHvF4B0knEiMwZWvlf
Authorization: Bearer usertoken
### Получение товаров в корзине
GET http://localhost/api/cart.get
# X-Session: dBQm7Ul0Tdw3JunyVHpmTZ2aMwnf4VLqVcNYeIWXvCSFBMmCYhf4vCPHFMCn82tD
Authorization: Bearer usertoken
###
GET http://localhost/api/cart.info
# X-Session: dBQm7Ul0Tdw3JunyVHpmTZ2aMwnf4VLqVcNYeIWXvCSFBMmCYhf4vCPHFMCn82tD
# Authorization: Bearer usertoken
### Увеличение количества позиции на 1
POST http://localhost/api/cart.increment
# X-Session: dBQm7Ul0Tdw3JunyVHpmTZ2aMwnf4VLqVcNYeIWXvCSFBMmCYhf4vCPHFMCn82tD
Authorization: Bearer usertoken
Content-Type: application/json

{
    "position_id":7
}
### Уменьшение количества позиции на 1
POST http://localhost/api/cart.decrement
# X-Session: WuqN1tjZWW5suU4nCyCABeijpz1SEbUl2RGpRq2zh4M0nliHvF4B0knEiMwZWvlf
Authorization: Bearer 7D4Fg0NfAOrYUnW6QeFNyTysYxUkF13dcPtnW3l1NENvAKHqyTR66SH3HZ30Nxar
Content-Type: application/json

{
    "position_id":11
}
