POST http://localhost/api/products.get
Content-Type: application/json

{
    "page_size":5,
    "page":1,
    # "search_string":"aperiam",
    "category_slug": "et",
    "sort_price":-1,
    "sort_new":true
}
###
GET http://localhost/api/products.meta
###
GET http://localhost/api/product.get?slug=optio
###
GET http://localhost/api/products.new
###
GET http://angrybro.sytes.net/api/products.meta
###
GET http://angrybro.sytes.net/api/products.new