### Получить все
GET http://localhost/api/colors.all
Authorization: Bearer admintoken
### Получить один
GET http://localhost/api/color.get?id=4
Authorization: Bearer admintoken
### Создать
POST http://localhost/api/color.create
Authorization: Bearer admintoken
Content-Type: application/json

{
    "name":"red",
    "rgb":"10,10,10",
    "article":"R"
}
### Обновить
POST http://localhost/api/color.update
Authorization: Bearer admintoken
Content-Type: application/json

{
    "id":4,
    "rgb":"20,20,20"
}
### Удалить
POST http://localhost/api/color.delete
Authorization: Bearer admintoken
Content-Type: application/json

{
    "id":4
}