### Получить картинку
GET http://localhost/api/img.get?ile=dQ70E5qndV6GmuBT9o0
### Загрузить картинку
POST http://localhost/api/img.upload
Authorization: Bearer admintoken
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photo"; filename="testimg.png"
Content-Type: image

< ./testimg.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###
POST http://localhost/api/img.delete
Authorization: Bearer admintoken
Content-Type: application/json

{
    "photo": "SZOG09BpCxDzvZU4iupk"
}