### Получить все нескрытые страницы
GET http://localhost/api/infopages.all
### Получить все страницы для админа
GET http://localhost/api/admin/infopages.all
Authorization: Bearer admintoken
### Получить нескрытую страницу
GET http://localhost/api/infopage.get?slug=asperiores
### Получить админу страницу
GET http://localhost/api/admin/infopage.get?slug=asperiores
Authorization: Bearer admintoken
### Обновить данные страницы
POST http://localhost/api/infopage.update
Authorization: Bearer admintoken
Content-Type: application/json

{
    "id":6,
    "hidden":false
    # "images":["asdnas", "adsad"]
}
### Создать страницу
POST http://logoshop.sytes.net:8888/api/infopage.create
Authorization: Bearer k8yWLeMuBhnHRyKrbRkCqD0PWZ7m5WQijavqJ6jUPqALyTB1DCrDt6OUCZJX4qHe
Content-Type: application/json

{
    "header":"Возврат",
    "slug":"back",
    "text1":"Текст о возврате\n текст",
    "text2":"Другой текст\n\n123",
    "image_header":"x5WOz9BLuC",
    "images":["baleuI7M0w","1adsasdas"],
    "place": 1
}
###
POST http://localhost/api/infopage.delete
Authorization: Bearer admintoken
Content-Type: application/json

{
    "id":20
}