### Создание заказа
POST http://localhost/api/order.create
Content-Type: application/json
Authorization: Bearer tYCP0fj1p0lDhKYx7VDDZldZouVV29qyyAenh34sfUv4ad9gh6IUlBsV38O10XKu

{
    "email":"user@user.ru",
    "delivery":false,
    "city":"Комсомольск",
    "street":"Пирогова",
    "building":"21",
    "index":681010
}
### Получение всех заказов
GET http://localhost/api/orders.all?page=1&page_size=4
Authorization: Bearer admintoken
### Получение одного заказа по id
GET http://localhost/api/order.get?id=1
Authorization: Bearer admintoken