### Создание подписки
POST http://localhost/api/subscribes.create
Authorization: Bearer usertoken
Content-Type: application/json

{
    "product_id":1,
    "size":"XS"
}
### Получение количества товаров появившихся в наличии
GET http://localhost/api/subscribes.count
Authorization: Bearer usertoken
### Получение id товаров и размеров в подписках
GET http://localhost/api/subscribes.getIds
Authorization: Bearer usertoken
### Получение списка товаров появившихся в наличии
GET http://localhost/api/subscribes.get
Authorization: Bearer usertoken
