### Создание подписки
POST http://localhost/api/subscribes.create
Authorization: Bearer 7cgmV3W7k0F150Q4NedFaiENMCAL29ZBYW3idom1tIYtnvweykqhJjnQdY6wwfzm
Content-Type: application/json

{
    "product_id":3,
    "size":"M"
}
### Получение количества товаров появившихся в наличии
GET http://localhost/api/subscribes.count
Authorization: Bearer 7cgmV3W7k0F150Q4NedFaiENMCAL29ZBYW3idom1tIYtnvweykqhJjnQdY6wwfzm
### Получение id товаров и размеров в подписках
GET http://localhost/api/subscribes.getIds
Authorization: Bearer 7cgmV3W7k0F150Q4NedFaiENMCAL29ZBYW3idom1tIYtnvweykqhJjnQdY6wwfzm
### Получение списка товаров появившихся в наличии
GET http://localhost/api/subscribes.get
Authorization: Bearer 7cgmV3W7k0F150Q4NedFaiENMCAL29ZBYW3idom1tIYtnvweykqhJjnQdY6wwfzm
